
apiVersion: v1
kind: Service
metadata:
  name: kafka-producer
spec:
  type: NodePort
  selector:
    app: kafka-producer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30088
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
        - name: kafka-producer
          image: krishnasravi/kafka-producer:v1.8
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
